#!/bin/bash

des_dir=""
script_dir="/usr/local/share/aliyun-assist/$assist_version/init"
src_dir=$script_dir
echo "script_dir:$script_dir"
echo "assist_version:$assist_version"

issue=""
. "$script_dir/script/common/identify_issue_version"
echo "issue:$issue"

if [ ! -e $script_dir/script/$issue/common/update_service ]; then
    echo "3131:failed to find update script."
    #exit 1
else
    ######### compare the pv in vm and newest pv##########
    . "$script_dir/script/$issue/common/update_service"
    if [ $? -ne 0 ]; then
        echo "3131:failed to find update gshelld script."
        #exit 1
    fi
fi


#echo "0:success"
