// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agrpc.proto

package agrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RespStatus struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	ErrMessage           string   `protobuf:"bytes,2,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespStatus) Reset()         { *m = RespStatus{} }
func (m *RespStatus) String() string { return proto.CompactTextString(m) }
func (*RespStatus) ProtoMessage()    {}
func (*RespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{0}
}

func (m *RespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespStatus.Unmarshal(m, b)
}
func (m *RespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespStatus.Marshal(b, m, deterministic)
}
func (m *RespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespStatus.Merge(m, src)
}
func (m *RespStatus) XXX_Size() int {
	return xxx_messageInfo_RespStatus.Size(m)
}
func (m *RespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RespStatus proto.InternalMessageInfo

func (m *RespStatus) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespStatus) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

type KeyInfo struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PublicKey            string   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CreatedTimestamp     int64    `protobuf:"varint,3,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	ExpiredTimestamp     int64    `protobuf:"varint,4,opt,name=expiredTimestamp,proto3" json:"expiredTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyInfo) Reset()         { *m = KeyInfo{} }
func (m *KeyInfo) String() string { return proto.CompactTextString(m) }
func (*KeyInfo) ProtoMessage()    {}
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{1}
}

func (m *KeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyInfo.Unmarshal(m, b)
}
func (m *KeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyInfo.Marshal(b, m, deterministic)
}
func (m *KeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyInfo.Merge(m, src)
}
func (m *KeyInfo) XXX_Size() int {
	return xxx_messageInfo_KeyInfo.Size(m)
}
func (m *KeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_KeyInfo proto.InternalMessageInfo

func (m *KeyInfo) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *KeyInfo) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *KeyInfo) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *KeyInfo) GetExpiredTimestamp() int64 {
	if m != nil {
		return m.ExpiredTimestamp
	}
	return 0
}

// GenRsaKeyPair api
type GenRsaKeyPairReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	Timeout              int32    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenRsaKeyPairReq) Reset()         { *m = GenRsaKeyPairReq{} }
func (m *GenRsaKeyPairReq) String() string { return proto.CompactTextString(m) }
func (*GenRsaKeyPairReq) ProtoMessage()    {}
func (*GenRsaKeyPairReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{2}
}

func (m *GenRsaKeyPairReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenRsaKeyPairReq.Unmarshal(m, b)
}
func (m *GenRsaKeyPairReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenRsaKeyPairReq.Marshal(b, m, deterministic)
}
func (m *GenRsaKeyPairReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenRsaKeyPairReq.Merge(m, src)
}
func (m *GenRsaKeyPairReq) XXX_Size() int {
	return xxx_messageInfo_GenRsaKeyPairReq.Size(m)
}
func (m *GenRsaKeyPairReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GenRsaKeyPairReq.DiscardUnknown(m)
}

var xxx_messageInfo_GenRsaKeyPairReq proto.InternalMessageInfo

func (m *GenRsaKeyPairReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *GenRsaKeyPairReq) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type GenRsaKeyPairResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	KeyInfo              *KeyInfo    `protobuf:"bytes,2,opt,name=keyInfo,proto3" json:"keyInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GenRsaKeyPairResp) Reset()         { *m = GenRsaKeyPairResp{} }
func (m *GenRsaKeyPairResp) String() string { return proto.CompactTextString(m) }
func (*GenRsaKeyPairResp) ProtoMessage()    {}
func (*GenRsaKeyPairResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{3}
}

func (m *GenRsaKeyPairResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenRsaKeyPairResp.Unmarshal(m, b)
}
func (m *GenRsaKeyPairResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenRsaKeyPairResp.Marshal(b, m, deterministic)
}
func (m *GenRsaKeyPairResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenRsaKeyPairResp.Merge(m, src)
}
func (m *GenRsaKeyPairResp) XXX_Size() int {
	return xxx_messageInfo_GenRsaKeyPairResp.Size(m)
}
func (m *GenRsaKeyPairResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GenRsaKeyPairResp.DiscardUnknown(m)
}

var xxx_messageInfo_GenRsaKeyPairResp proto.InternalMessageInfo

func (m *GenRsaKeyPairResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GenRsaKeyPairResp) GetKeyInfo() *KeyInfo {
	if m != nil {
		return m.KeyInfo
	}
	return nil
}

// RemoveRsaKeyPair api
type RemoveRsaKeyPairReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRsaKeyPairReq) Reset()         { *m = RemoveRsaKeyPairReq{} }
func (m *RemoveRsaKeyPairReq) String() string { return proto.CompactTextString(m) }
func (*RemoveRsaKeyPairReq) ProtoMessage()    {}
func (*RemoveRsaKeyPairReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{4}
}

func (m *RemoveRsaKeyPairReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRsaKeyPairReq.Unmarshal(m, b)
}
func (m *RemoveRsaKeyPairReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRsaKeyPairReq.Marshal(b, m, deterministic)
}
func (m *RemoveRsaKeyPairReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRsaKeyPairReq.Merge(m, src)
}
func (m *RemoveRsaKeyPairReq) XXX_Size() int {
	return xxx_messageInfo_RemoveRsaKeyPairReq.Size(m)
}
func (m *RemoveRsaKeyPairReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRsaKeyPairReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRsaKeyPairReq proto.InternalMessageInfo

func (m *RemoveRsaKeyPairReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

type RemoveRsaKeyPairResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RemoveRsaKeyPairResp) Reset()         { *m = RemoveRsaKeyPairResp{} }
func (m *RemoveRsaKeyPairResp) String() string { return proto.CompactTextString(m) }
func (*RemoveRsaKeyPairResp) ProtoMessage()    {}
func (*RemoveRsaKeyPairResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{5}
}

func (m *RemoveRsaKeyPairResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRsaKeyPairResp.Unmarshal(m, b)
}
func (m *RemoveRsaKeyPairResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRsaKeyPairResp.Marshal(b, m, deterministic)
}
func (m *RemoveRsaKeyPairResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRsaKeyPairResp.Merge(m, src)
}
func (m *RemoveRsaKeyPairResp) XXX_Size() int {
	return xxx_messageInfo_RemoveRsaKeyPairResp.Size(m)
}
func (m *RemoveRsaKeyPairResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRsaKeyPairResp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRsaKeyPairResp proto.InternalMessageInfo

func (m *RemoveRsaKeyPairResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// Encrypt api
type EncryptReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PlainText            string   `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptReq) Reset()         { *m = EncryptReq{} }
func (m *EncryptReq) String() string { return proto.CompactTextString(m) }
func (*EncryptReq) ProtoMessage()    {}
func (*EncryptReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{6}
}

func (m *EncryptReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptReq.Unmarshal(m, b)
}
func (m *EncryptReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptReq.Marshal(b, m, deterministic)
}
func (m *EncryptReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptReq.Merge(m, src)
}
func (m *EncryptReq) XXX_Size() int {
	return xxx_messageInfo_EncryptReq.Size(m)
}
func (m *EncryptReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptReq.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptReq proto.InternalMessageInfo

func (m *EncryptReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *EncryptReq) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

type EncryptResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CipherText           string      `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EncryptResp) Reset()         { *m = EncryptResp{} }
func (m *EncryptResp) String() string { return proto.CompactTextString(m) }
func (*EncryptResp) ProtoMessage()    {}
func (*EncryptResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{7}
}

func (m *EncryptResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptResp.Unmarshal(m, b)
}
func (m *EncryptResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptResp.Marshal(b, m, deterministic)
}
func (m *EncryptResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptResp.Merge(m, src)
}
func (m *EncryptResp) XXX_Size() int {
	return xxx_messageInfo_EncryptResp.Size(m)
}
func (m *EncryptResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptResp.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptResp proto.InternalMessageInfo

func (m *EncryptResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *EncryptResp) GetCipherText() string {
	if m != nil {
		return m.CipherText
	}
	return ""
}

// Decrypt api
type DecryptReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	CipherText           string   `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptReq) Reset()         { *m = DecryptReq{} }
func (m *DecryptReq) String() string { return proto.CompactTextString(m) }
func (*DecryptReq) ProtoMessage()    {}
func (*DecryptReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{8}
}

func (m *DecryptReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptReq.Unmarshal(m, b)
}
func (m *DecryptReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptReq.Marshal(b, m, deterministic)
}
func (m *DecryptReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptReq.Merge(m, src)
}
func (m *DecryptReq) XXX_Size() int {
	return xxx_messageInfo_DecryptReq.Size(m)
}
func (m *DecryptReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptReq.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptReq proto.InternalMessageInfo

func (m *DecryptReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *DecryptReq) GetCipherText() string {
	if m != nil {
		return m.CipherText
	}
	return ""
}

type DecryptResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PlainText            string      `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DecryptResp) Reset()         { *m = DecryptResp{} }
func (m *DecryptResp) String() string { return proto.CompactTextString(m) }
func (*DecryptResp) ProtoMessage()    {}
func (*DecryptResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{9}
}

func (m *DecryptResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptResp.Unmarshal(m, b)
}
func (m *DecryptResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptResp.Marshal(b, m, deterministic)
}
func (m *DecryptResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptResp.Merge(m, src)
}
func (m *DecryptResp) XXX_Size() int {
	return xxx_messageInfo_DecryptResp.Size(m)
}
func (m *DecryptResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptResp.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptResp proto.InternalMessageInfo

func (m *DecryptResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DecryptResp) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

// CheckKey api
type CheckKeyReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckKeyReq) Reset()         { *m = CheckKeyReq{} }
func (m *CheckKeyReq) String() string { return proto.CompactTextString(m) }
func (*CheckKeyReq) ProtoMessage()    {}
func (*CheckKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{10}
}

func (m *CheckKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckKeyReq.Unmarshal(m, b)
}
func (m *CheckKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckKeyReq.Marshal(b, m, deterministic)
}
func (m *CheckKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckKeyReq.Merge(m, src)
}
func (m *CheckKeyReq) XXX_Size() int {
	return xxx_messageInfo_CheckKeyReq.Size(m)
}
func (m *CheckKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckKeyReq proto.InternalMessageInfo

func (m *CheckKeyReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

type CheckKeyResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	KeyInfos             []*KeyInfo  `protobuf:"bytes,2,rep,name=keyInfos,proto3" json:"keyInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckKeyResp) Reset()         { *m = CheckKeyResp{} }
func (m *CheckKeyResp) String() string { return proto.CompactTextString(m) }
func (*CheckKeyResp) ProtoMessage()    {}
func (*CheckKeyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{11}
}

func (m *CheckKeyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckKeyResp.Unmarshal(m, b)
}
func (m *CheckKeyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckKeyResp.Marshal(b, m, deterministic)
}
func (m *CheckKeyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckKeyResp.Merge(m, src)
}
func (m *CheckKeyResp) XXX_Size() int {
	return xxx_messageInfo_CheckKeyResp.Size(m)
}
func (m *CheckKeyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckKeyResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckKeyResp proto.InternalMessageInfo

func (m *CheckKeyResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CheckKeyResp) GetKeyInfos() []*KeyInfo {
	if m != nil {
		return m.KeyInfos
	}
	return nil
}

type SecretParamInfo struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	CreatedTimestamp     int64    `protobuf:"varint,2,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	ExpiredTimestamp     int64    `protobuf:"varint,3,opt,name=expiredTimestamp,proto3" json:"expiredTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretParamInfo) Reset()         { *m = SecretParamInfo{} }
func (m *SecretParamInfo) String() string { return proto.CompactTextString(m) }
func (*SecretParamInfo) ProtoMessage()    {}
func (*SecretParamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{12}
}

func (m *SecretParamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretParamInfo.Unmarshal(m, b)
}
func (m *SecretParamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretParamInfo.Marshal(b, m, deterministic)
}
func (m *SecretParamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretParamInfo.Merge(m, src)
}
func (m *SecretParamInfo) XXX_Size() int {
	return xxx_messageInfo_SecretParamInfo.Size(m)
}
func (m *SecretParamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretParamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SecretParamInfo proto.InternalMessageInfo

func (m *SecretParamInfo) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *SecretParamInfo) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *SecretParamInfo) GetExpiredTimestamp() int64 {
	if m != nil {
		return m.ExpiredTimestamp
	}
	return 0
}

// CreateSecret api
type CreateSecretParamReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	CipherText           string   `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	SecretName           string   `protobuf:"bytes,3,opt,name=secretName,proto3" json:"secretName,omitempty"`
	Timeout              int32    `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	CipherAesKey         string   `protobuf:"bytes,5,opt,name=cipherAesKey,proto3" json:"cipherAesKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSecretParamReq) Reset()         { *m = CreateSecretParamReq{} }
func (m *CreateSecretParamReq) String() string { return proto.CompactTextString(m) }
func (*CreateSecretParamReq) ProtoMessage()    {}
func (*CreateSecretParamReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{13}
}

func (m *CreateSecretParamReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretParamReq.Unmarshal(m, b)
}
func (m *CreateSecretParamReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretParamReq.Marshal(b, m, deterministic)
}
func (m *CreateSecretParamReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretParamReq.Merge(m, src)
}
func (m *CreateSecretParamReq) XXX_Size() int {
	return xxx_messageInfo_CreateSecretParamReq.Size(m)
}
func (m *CreateSecretParamReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretParamReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretParamReq proto.InternalMessageInfo

func (m *CreateSecretParamReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *CreateSecretParamReq) GetCipherText() string {
	if m != nil {
		return m.CipherText
	}
	return ""
}

func (m *CreateSecretParamReq) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *CreateSecretParamReq) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *CreateSecretParamReq) GetCipherAesKey() string {
	if m != nil {
		return m.CipherAesKey
	}
	return ""
}

type CreateSecretParamResp struct {
	Status               *RespStatus      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SecretParam          *SecretParamInfo `protobuf:"bytes,2,opt,name=secretParam,proto3" json:"secretParam,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateSecretParamResp) Reset()         { *m = CreateSecretParamResp{} }
func (m *CreateSecretParamResp) String() string { return proto.CompactTextString(m) }
func (*CreateSecretParamResp) ProtoMessage()    {}
func (*CreateSecretParamResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{14}
}

func (m *CreateSecretParamResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSecretParamResp.Unmarshal(m, b)
}
func (m *CreateSecretParamResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSecretParamResp.Marshal(b, m, deterministic)
}
func (m *CreateSecretParamResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSecretParamResp.Merge(m, src)
}
func (m *CreateSecretParamResp) XXX_Size() int {
	return xxx_messageInfo_CreateSecretParamResp.Size(m)
}
func (m *CreateSecretParamResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSecretParamResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSecretParamResp proto.InternalMessageInfo

func (m *CreateSecretParamResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateSecretParamResp) GetSecretParam() *SecretParamInfo {
	if m != nil {
		return m.SecretParam
	}
	return nil
}

type SecretParamValue struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	SecretValue          string   `protobuf:"bytes,2,opt,name=secretValue,proto3" json:"secretValue,omitempty"`
	CreatedTimestamp     int64    `protobuf:"varint,3,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	ExpiredTimestamp     int64    `protobuf:"varint,4,opt,name=expiredTimestamp,proto3" json:"expiredTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretParamValue) Reset()         { *m = SecretParamValue{} }
func (m *SecretParamValue) String() string { return proto.CompactTextString(m) }
func (*SecretParamValue) ProtoMessage()    {}
func (*SecretParamValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{15}
}

func (m *SecretParamValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretParamValue.Unmarshal(m, b)
}
func (m *SecretParamValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretParamValue.Marshal(b, m, deterministic)
}
func (m *SecretParamValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretParamValue.Merge(m, src)
}
func (m *SecretParamValue) XXX_Size() int {
	return xxx_messageInfo_SecretParamValue.Size(m)
}
func (m *SecretParamValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretParamValue.DiscardUnknown(m)
}

var xxx_messageInfo_SecretParamValue proto.InternalMessageInfo

func (m *SecretParamValue) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

func (m *SecretParamValue) GetSecretValue() string {
	if m != nil {
		return m.SecretValue
	}
	return ""
}

func (m *SecretParamValue) GetCreatedTimestamp() int64 {
	if m != nil {
		return m.CreatedTimestamp
	}
	return 0
}

func (m *SecretParamValue) GetExpiredTimestamp() int64 {
	if m != nil {
		return m.ExpiredTimestamp
	}
	return 0
}

// GetSecretValue
type GetSecretParamValueReq struct {
	SecretName           string   `protobuf:"bytes,1,opt,name=secretName,proto3" json:"secretName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSecretParamValueReq) Reset()         { *m = GetSecretParamValueReq{} }
func (m *GetSecretParamValueReq) String() string { return proto.CompactTextString(m) }
func (*GetSecretParamValueReq) ProtoMessage()    {}
func (*GetSecretParamValueReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{16}
}

func (m *GetSecretParamValueReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretParamValueReq.Unmarshal(m, b)
}
func (m *GetSecretParamValueReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretParamValueReq.Marshal(b, m, deterministic)
}
func (m *GetSecretParamValueReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretParamValueReq.Merge(m, src)
}
func (m *GetSecretParamValueReq) XXX_Size() int {
	return xxx_messageInfo_GetSecretParamValueReq.Size(m)
}
func (m *GetSecretParamValueReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretParamValueReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretParamValueReq proto.InternalMessageInfo

func (m *GetSecretParamValueReq) GetSecretName() string {
	if m != nil {
		return m.SecretName
	}
	return ""
}

type GetSecretParamValueResp struct {
	Status               *RespStatus       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SecretParamValue     *SecretParamValue `protobuf:"bytes,2,opt,name=secretParamValue,proto3" json:"secretParamValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSecretParamValueResp) Reset()         { *m = GetSecretParamValueResp{} }
func (m *GetSecretParamValueResp) String() string { return proto.CompactTextString(m) }
func (*GetSecretParamValueResp) ProtoMessage()    {}
func (*GetSecretParamValueResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{17}
}

func (m *GetSecretParamValueResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretParamValueResp.Unmarshal(m, b)
}
func (m *GetSecretParamValueResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretParamValueResp.Marshal(b, m, deterministic)
}
func (m *GetSecretParamValueResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretParamValueResp.Merge(m, src)
}
func (m *GetSecretParamValueResp) XXX_Size() int {
	return xxx_messageInfo_GetSecretParamValueResp.Size(m)
}
func (m *GetSecretParamValueResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretParamValueResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretParamValueResp proto.InternalMessageInfo

func (m *GetSecretParamValueResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetSecretParamValueResp) GetSecretParamValue() *SecretParamValue {
	if m != nil {
		return m.SecretParamValue
	}
	return nil
}

// SignData
type SignDataReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PlainText            string   `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignDataReq) Reset()         { *m = SignDataReq{} }
func (m *SignDataReq) String() string { return proto.CompactTextString(m) }
func (*SignDataReq) ProtoMessage()    {}
func (*SignDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{18}
}

func (m *SignDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDataReq.Unmarshal(m, b)
}
func (m *SignDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDataReq.Marshal(b, m, deterministic)
}
func (m *SignDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDataReq.Merge(m, src)
}
func (m *SignDataReq) XXX_Size() int {
	return xxx_messageInfo_SignDataReq.Size(m)
}
func (m *SignDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignDataReq proto.InternalMessageInfo

func (m *SignDataReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *SignDataReq) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

type SignDataResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Signature            string      `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignDataResp) Reset()         { *m = SignDataResp{} }
func (m *SignDataResp) String() string { return proto.CompactTextString(m) }
func (*SignDataResp) ProtoMessage()    {}
func (*SignDataResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{19}
}

func (m *SignDataResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignDataResp.Unmarshal(m, b)
}
func (m *SignDataResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignDataResp.Marshal(b, m, deterministic)
}
func (m *SignDataResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignDataResp.Merge(m, src)
}
func (m *SignDataResp) XXX_Size() int {
	return xxx_messageInfo_SignDataResp.Size(m)
}
func (m *SignDataResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignDataResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignDataResp proto.InternalMessageInfo

func (m *SignDataResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignDataResp) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// VerifySignature
type VerifySignatureReq struct {
	KeyPairId            string   `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PlainText            string   `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySignatureReq) Reset()         { *m = VerifySignatureReq{} }
func (m *VerifySignatureReq) String() string { return proto.CompactTextString(m) }
func (*VerifySignatureReq) ProtoMessage()    {}
func (*VerifySignatureReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{20}
}

func (m *VerifySignatureReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySignatureReq.Unmarshal(m, b)
}
func (m *VerifySignatureReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySignatureReq.Marshal(b, m, deterministic)
}
func (m *VerifySignatureReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySignatureReq.Merge(m, src)
}
func (m *VerifySignatureReq) XXX_Size() int {
	return xxx_messageInfo_VerifySignatureReq.Size(m)
}
func (m *VerifySignatureReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySignatureReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySignatureReq proto.InternalMessageInfo

func (m *VerifySignatureReq) GetKeyPairId() string {
	if m != nil {
		return m.KeyPairId
	}
	return ""
}

func (m *VerifySignatureReq) GetPlainText() string {
	if m != nil {
		return m.PlainText
	}
	return ""
}

func (m *VerifySignatureReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type VerifySignatureResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Valid                bool        `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifySignatureResp) Reset()         { *m = VerifySignatureResp{} }
func (m *VerifySignatureResp) String() string { return proto.CompactTextString(m) }
func (*VerifySignatureResp) ProtoMessage()    {}
func (*VerifySignatureResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9840c882bb9a7ad, []int{21}
}

func (m *VerifySignatureResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySignatureResp.Unmarshal(m, b)
}
func (m *VerifySignatureResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySignatureResp.Marshal(b, m, deterministic)
}
func (m *VerifySignatureResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySignatureResp.Merge(m, src)
}
func (m *VerifySignatureResp) XXX_Size() int {
	return xxx_messageInfo_VerifySignatureResp.Size(m)
}
func (m *VerifySignatureResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySignatureResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySignatureResp proto.InternalMessageInfo

func (m *VerifySignatureResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VerifySignatureResp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*RespStatus)(nil), "protos.RespStatus")
	proto.RegisterType((*KeyInfo)(nil), "protos.KeyInfo")
	proto.RegisterType((*GenRsaKeyPairReq)(nil), "protos.GenRsaKeyPairReq")
	proto.RegisterType((*GenRsaKeyPairResp)(nil), "protos.GenRsaKeyPairResp")
	proto.RegisterType((*RemoveRsaKeyPairReq)(nil), "protos.RemoveRsaKeyPairReq")
	proto.RegisterType((*RemoveRsaKeyPairResp)(nil), "protos.RemoveRsaKeyPairResp")
	proto.RegisterType((*EncryptReq)(nil), "protos.EncryptReq")
	proto.RegisterType((*EncryptResp)(nil), "protos.EncryptResp")
	proto.RegisterType((*DecryptReq)(nil), "protos.DecryptReq")
	proto.RegisterType((*DecryptResp)(nil), "protos.DecryptResp")
	proto.RegisterType((*CheckKeyReq)(nil), "protos.CheckKeyReq")
	proto.RegisterType((*CheckKeyResp)(nil), "protos.CheckKeyResp")
	proto.RegisterType((*SecretParamInfo)(nil), "protos.SecretParamInfo")
	proto.RegisterType((*CreateSecretParamReq)(nil), "protos.CreateSecretParamReq")
	proto.RegisterType((*CreateSecretParamResp)(nil), "protos.CreateSecretParamResp")
	proto.RegisterType((*SecretParamValue)(nil), "protos.SecretParamValue")
	proto.RegisterType((*GetSecretParamValueReq)(nil), "protos.GetSecretParamValueReq")
	proto.RegisterType((*GetSecretParamValueResp)(nil), "protos.GetSecretParamValueResp")
	proto.RegisterType((*SignDataReq)(nil), "protos.SignDataReq")
	proto.RegisterType((*SignDataResp)(nil), "protos.SignDataResp")
	proto.RegisterType((*VerifySignatureReq)(nil), "protos.VerifySignatureReq")
	proto.RegisterType((*VerifySignatureResp)(nil), "protos.VerifySignatureResp")
}

func init() {
	proto.RegisterFile("agrpc.proto", fileDescriptor_d9840c882bb9a7ad)
}

var fileDescriptor_d9840c882bb9a7ad = []byte{
	// 823 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0xf6, 0x5a, 0x51, 0x6c, 0xf7, 0x8a, 0xb2, 0x32, 0x12, 0x44, 0x6c, 0x82, 0x51, 0xcd, 0xc9,
	0x90, 0x2a, 0xab, 0xca, 0x39, 0x10, 0x8e, 0x8e, 0x1c, 0x82, 0xa3, 0x40, 0xa5, 0x56, 0x29, 0xdb,
	0x70, 0x71, 0x8d, 0x57, 0x6d, 0x79, 0xb0, 0xf6, 0x87, 0x9d, 0x91, 0xcb, 0xba, 0x70, 0xe2, 0x42,
	0xf1, 0x0c, 0xbc, 0x01, 0x27, 0x9e, 0x90, 0xda, 0xd9, 0xbf, 0xd1, 0xee, 0xca, 0x62, 0xcb, 0xc5,
	0x49, 0xd2, 0x37, 0xdd, 0xdf, 0x7c, 0xdd, 0x3d, 0xdd, 0x2d, 0x30, 0xd9, 0x34, 0x0c, 0x9c, 0x83,
	0x20, 0xf4, 0xa5, 0x4f, 0x1e, 0xab, 0x0f, 0x41, 0xdf, 0x03, 0xd8, 0x28, 0x82, 0xb1, 0x64, 0x72,
	0x2e, 0xc8, 0x1e, 0x80, 0x50, 0xdf, 0x86, 0xfe, 0x04, 0x7b, 0x46, 0xdf, 0xd8, 0x6f, 0xda, 0x1a,
	0x12, 0x9d, 0x63, 0x18, 0xfe, 0x80, 0x42, 0xb0, 0x29, 0xf6, 0x36, 0xfb, 0xc6, 0xfe, 0x8e, 0xad,
	0x21, 0xf4, 0x2f, 0x03, 0xb6, 0x46, 0xb8, 0x38, 0xf1, 0xae, 0x7c, 0xf2, 0x1c, 0x76, 0x6e, 0x70,
	0xf1, 0x81, 0xf1, 0xf0, 0x64, 0xa2, 0xa8, 0x76, 0xec, 0x1c, 0x88, 0x4e, 0x83, 0xf9, 0xe5, 0x8c,
	0x3b, 0x23, 0x5c, 0x24, 0x44, 0x39, 0x40, 0xbe, 0x86, 0xb6, 0x13, 0x22, 0x93, 0x38, 0xf9, 0xc8,
	0x5d, 0x14, 0x92, 0xb9, 0x41, 0xaf, 0xd1, 0x37, 0xf6, 0x1b, 0x76, 0x09, 0x8f, 0x6c, 0xf1, 0x2e,
	0xe0, 0xa1, 0x6e, 0xfb, 0x28, 0xb6, 0x2d, 0xe2, 0xf4, 0x1d, 0xb4, 0xdf, 0xa2, 0x67, 0x0b, 0x36,
	0x8a, 0x85, 0xd8, 0xf8, 0xeb, 0x1a, 0x9d, 0x3d, 0xd8, 0x92, 0xdc, 0x45, 0x7f, 0x2e, 0x95, 0xca,
	0xa6, 0x9d, 0xfe, 0xa4, 0xbf, 0xc0, 0x93, 0x02, 0x97, 0x88, 0xc4, 0x3c, 0x8e, 0xd3, 0xa5, 0x98,
	0xcc, 0x43, 0x12, 0xa7, 0x5b, 0x1c, 0xe4, 0x49, 0xb6, 0x13, 0x0b, 0xf2, 0x15, 0x6c, 0xdd, 0xc4,
	0xb9, 0x52, 0xd4, 0xe6, 0xe1, 0x6e, 0x6a, 0x9c, 0xa4, 0xd0, 0x4e, 0xcf, 0xe9, 0x4b, 0xe8, 0xd8,
	0xe8, 0xfa, 0xb7, 0x58, 0x43, 0x3a, 0x7d, 0x0d, 0xdd, 0xb2, 0x53, 0x3d, 0x8d, 0xf4, 0x7b, 0x80,
	0x37, 0x9e, 0x13, 0x2e, 0x02, 0xb9, 0x3e, 0x55, 0x51, 0x49, 0x67, 0x8c, 0x7b, 0x1f, 0xf1, 0x4e,
	0x66, 0x25, 0x4d, 0x01, 0xfa, 0x13, 0x98, 0x19, 0x53, 0xcd, 0x44, 0xed, 0x01, 0x38, 0x3c, 0xb8,
	0xc6, 0x50, 0x63, 0xd6, 0x10, 0xfa, 0x0e, 0xe0, 0x18, 0xff, 0xa3, 0xc8, 0x75, 0x5c, 0x67, 0x60,
	0x66, 0x5c, 0x35, 0x65, 0xde, 0x1f, 0xff, 0x0b, 0x30, 0x87, 0xd7, 0xe8, 0xdc, 0x8c, 0x70, 0xb1,
	0xbe, 0x74, 0x53, 0x68, 0xe5, 0xc6, 0x35, 0x65, 0xbc, 0x80, 0xed, 0xe4, 0xd9, 0x88, 0xde, 0x66,
	0xbf, 0x51, 0xf5, 0xae, 0x32, 0x03, 0xfa, 0x87, 0x01, 0xbb, 0x63, 0x74, 0x42, 0x94, 0x1f, 0x58,
	0xc8, 0x5c, 0xd5, 0xb8, 0xd1, 0x10, 0x50, 0xd0, 0x8f, 0xcc, 0xc5, 0x44, 0x9b, 0x86, 0x54, 0x36,
	0xe7, 0x66, 0x8d, 0xe6, 0x6c, 0xac, 0x68, 0xce, 0x7f, 0x0c, 0xe8, 0x0e, 0x15, 0x81, 0xa6, 0xe8,
	0xc1, 0x15, 0x2d, 0x84, 0xd3, 0x28, 0x85, 0xa3, 0x75, 0xf8, 0xa3, 0xa5, 0x0e, 0x27, 0x14, 0x5a,
	0x31, 0xcf, 0x11, 0x8a, 0x68, 0x4c, 0x35, 0x95, 0xef, 0x12, 0x46, 0x7f, 0x83, 0x4f, 0x2b, 0x34,
	0xd7, 0x2c, 0xd9, 0xb7, 0x60, 0x8a, 0xdc, 0x3d, 0x99, 0x06, 0x4f, 0x53, 0x87, 0x42, 0x7d, 0x6c,
	0xdd, 0x96, 0xfe, 0x6d, 0x40, 0x5b, 0x33, 0x38, 0x65, 0xb3, 0x39, 0xae, 0xad, 0x60, 0x3f, 0xbd,
	0x4f, 0x99, 0x27, 0x39, 0xd3, 0xa1, 0xff, 0x6d, 0x00, 0xbf, 0x82, 0xcf, 0xde, 0xa2, 0x2c, 0x0a,
	0x8e, 0x8a, 0xbc, 0x46, 0x33, 0xfd, 0xd3, 0x80, 0xa7, 0x95, 0xae, 0x35, 0x73, 0x7d, 0x0c, 0x6d,
	0x51, 0xe0, 0x48, 0x12, 0xde, 0xab, 0x48, 0x78, 0x7c, 0x47, 0xc9, 0x83, 0x9e, 0x80, 0x39, 0xe6,
	0x53, 0xef, 0x98, 0x49, 0xf6, 0xd0, 0xc1, 0x78, 0x0e, 0xad, 0x9c, 0xaa, 0xfe, 0xc8, 0x11, 0x7c,
	0xea, 0x31, 0x39, 0x0f, 0xd3, 0x32, 0xe6, 0x00, 0xf5, 0x80, 0x9c, 0x62, 0xc8, 0xaf, 0x16, 0xe3,
	0x14, 0x7a, 0xa0, 0xd6, 0xe5, 0xfb, 0x1a, 0xc5, 0xfb, 0xce, 0xa0, 0x53, 0xba, 0xaf, 0x66, 0x40,
	0x5d, 0x68, 0xde, 0xb2, 0x19, 0x9f, 0xa8, 0xab, 0xb7, 0xed, 0xf8, 0xc7, 0xe1, 0xef, 0x4d, 0x30,
	0x8f, 0x84, 0xe0, 0x42, 0x1e, 0x4d, 0xd1, 0x93, 0xe4, 0x3b, 0xf8, 0x64, 0x69, 0xf5, 0x92, 0xac,
	0x74, 0xc5, 0xed, 0x6e, 0x7d, 0xbe, 0xe2, 0x44, 0x04, 0x74, 0x83, 0x8c, 0xa0, 0x65, 0xbb, 0x1a,
	0xcd, 0xb3, 0x5c, 0x59, 0x69, 0xd9, 0x5a, 0xcf, 0x57, 0x1f, 0x2a, 0xb2, 0x57, 0xd9, 0x82, 0x53,
	0xa9, 0xca, 0xa2, 0xcc, 0xf7, 0xa7, 0xd5, 0x29, 0x61, 0xa9, 0x67, 0xb2, 0x73, 0x96, 0x3d, 0xf3,
	0xa5, 0x96, 0x7b, 0x6a, 0xcb, 0x89, 0x6e, 0x90, 0x6f, 0x60, 0x3b, 0xdd, 0x13, 0x24, 0x33, 0xd1,
	0xd6, 0x8c, 0xd5, 0x2d, 0x83, 0xca, 0xd1, 0x86, 0x27, 0xa5, 0xb1, 0x45, 0xb2, 0x08, 0xab, 0xa6,
	0xb0, 0xf5, 0xc5, 0x3d, 0xa7, 0x8a, 0xf3, 0x1c, 0x3a, 0x15, 0x0d, 0x4a, 0xf6, 0xf2, 0x0a, 0x54,
	0x35, 0xbe, 0xf5, 0xe5, 0xbd, 0xe7, 0x69, 0x98, 0x69, 0x8b, 0xe4, 0x61, 0x6a, 0xfd, 0x97, 0x87,
	0xa9, 0x77, 0x12, 0xdd, 0x20, 0xef, 0x61, 0xb7, 0xf0, 0x22, 0x89, 0x95, 0x9a, 0x96, 0x5b, 0xc3,
	0x7a, 0xb6, 0xf2, 0x2c, 0x62, 0x7b, 0xfd, 0xe6, 0xe7, 0xe1, 0x94, 0xcb, 0xeb, 0xf9, 0xe5, 0x81,
	0xe3, 0xbb, 0x03, 0x36, 0xe3, 0x8b, 0xb9, 0x97, 0x7c, 0x5c, 0x30, 0xf5, 0x3c, 0x2f, 0x9c, 0x19,
	0x47, 0x4f, 0x0e, 0xb8, 0x27, 0x31, 0x0c, 0x42, 0xdf, 0x41, 0x21, 0x06, 0xaa, 0x60, 0x13, 0x26,
	0xd9, 0x40, 0xfd, 0x01, 0xbf, 0x8c, 0xff, 0x7a, 0xbf, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0x8d, 0x50, 0xbd, 0x90, 0x0b, 0x00, 0x00,
}
