// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: agrpc.proto

package agrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssistAgentClient is the client API for AssistAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistAgentClient interface {
	GenRsaKeyPair(ctx context.Context, in *GenRsaKeyPairReq, opts ...grpc.CallOption) (*GenRsaKeyPairResp, error)
	RmRsaKeyPair(ctx context.Context, in *RemoveRsaKeyPairReq, opts ...grpc.CallOption) (*RemoveRsaKeyPairResp, error)
	EncryptText(ctx context.Context, in *EncryptReq, opts ...grpc.CallOption) (*EncryptResp, error)
	DecryptText(ctx context.Context, in *DecryptReq, opts ...grpc.CallOption) (*DecryptResp, error)
	CheckKey(ctx context.Context, in *CheckKeyReq, opts ...grpc.CallOption) (*CheckKeyResp, error)
	CreateSecretParam(ctx context.Context, in *CreateSecretParamReq, opts ...grpc.CallOption) (*CreateSecretParamResp, error)
	GetSecretParamValue(ctx context.Context, in *GetSecretParamValueReq, opts ...grpc.CallOption) (*GetSecretParamValueResp, error)
	SignData(ctx context.Context, in *SignDataReq, opts ...grpc.CallOption) (*SignDataResp, error)
	VerifySignature(ctx context.Context, in *VerifySignatureReq, opts ...grpc.CallOption) (*VerifySignatureResp, error)
}

type assistAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistAgentClient(cc grpc.ClientConnInterface) AssistAgentClient {
	return &assistAgentClient{cc}
}

func (c *assistAgentClient) GenRsaKeyPair(ctx context.Context, in *GenRsaKeyPairReq, opts ...grpc.CallOption) (*GenRsaKeyPairResp, error) {
	out := new(GenRsaKeyPairResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/GenRsaKeyPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) RmRsaKeyPair(ctx context.Context, in *RemoveRsaKeyPairReq, opts ...grpc.CallOption) (*RemoveRsaKeyPairResp, error) {
	out := new(RemoveRsaKeyPairResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/RmRsaKeyPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) EncryptText(ctx context.Context, in *EncryptReq, opts ...grpc.CallOption) (*EncryptResp, error) {
	out := new(EncryptResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/EncryptText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) DecryptText(ctx context.Context, in *DecryptReq, opts ...grpc.CallOption) (*DecryptResp, error) {
	out := new(DecryptResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/DecryptText", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) CheckKey(ctx context.Context, in *CheckKeyReq, opts ...grpc.CallOption) (*CheckKeyResp, error) {
	out := new(CheckKeyResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/CheckKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) CreateSecretParam(ctx context.Context, in *CreateSecretParamReq, opts ...grpc.CallOption) (*CreateSecretParamResp, error) {
	out := new(CreateSecretParamResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/CreateSecretParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) GetSecretParamValue(ctx context.Context, in *GetSecretParamValueReq, opts ...grpc.CallOption) (*GetSecretParamValueResp, error) {
	out := new(GetSecretParamValueResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/GetSecretParamValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) SignData(ctx context.Context, in *SignDataReq, opts ...grpc.CallOption) (*SignDataResp, error) {
	out := new(SignDataResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/SignData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) VerifySignature(ctx context.Context, in *VerifySignatureReq, opts ...grpc.CallOption) (*VerifySignatureResp, error) {
	out := new(VerifySignatureResp)
	err := c.cc.Invoke(ctx, "/protos.AssistAgent/VerifySignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistAgentServer is the server API for AssistAgent service.
// All implementations must embed UnimplementedAssistAgentServer
// for forward compatibility
type AssistAgentServer interface {
	GenRsaKeyPair(context.Context, *GenRsaKeyPairReq) (*GenRsaKeyPairResp, error)
	RmRsaKeyPair(context.Context, *RemoveRsaKeyPairReq) (*RemoveRsaKeyPairResp, error)
	EncryptText(context.Context, *EncryptReq) (*EncryptResp, error)
	DecryptText(context.Context, *DecryptReq) (*DecryptResp, error)
	CheckKey(context.Context, *CheckKeyReq) (*CheckKeyResp, error)
	CreateSecretParam(context.Context, *CreateSecretParamReq) (*CreateSecretParamResp, error)
	GetSecretParamValue(context.Context, *GetSecretParamValueReq) (*GetSecretParamValueResp, error)
	SignData(context.Context, *SignDataReq) (*SignDataResp, error)
	VerifySignature(context.Context, *VerifySignatureReq) (*VerifySignatureResp, error)
	mustEmbedUnimplementedAssistAgentServer()
}

// UnimplementedAssistAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAssistAgentServer struct {
}

func (UnimplementedAssistAgentServer) GenRsaKeyPair(context.Context, *GenRsaKeyPairReq) (*GenRsaKeyPairResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenRsaKeyPair not implemented")
}
func (UnimplementedAssistAgentServer) RmRsaKeyPair(context.Context, *RemoveRsaKeyPairReq) (*RemoveRsaKeyPairResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RmRsaKeyPair not implemented")
}
func (UnimplementedAssistAgentServer) EncryptText(context.Context, *EncryptReq) (*EncryptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptText not implemented")
}
func (UnimplementedAssistAgentServer) DecryptText(context.Context, *DecryptReq) (*DecryptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptText not implemented")
}
func (UnimplementedAssistAgentServer) CheckKey(context.Context, *CheckKeyReq) (*CheckKeyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckKey not implemented")
}
func (UnimplementedAssistAgentServer) CreateSecretParam(context.Context, *CreateSecretParamReq) (*CreateSecretParamResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecretParam not implemented")
}
func (UnimplementedAssistAgentServer) GetSecretParamValue(context.Context, *GetSecretParamValueReq) (*GetSecretParamValueResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretParamValue not implemented")
}
func (UnimplementedAssistAgentServer) SignData(context.Context, *SignDataReq) (*SignDataResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignData not implemented")
}
func (UnimplementedAssistAgentServer) VerifySignature(context.Context, *VerifySignatureReq) (*VerifySignatureResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignature not implemented")
}
func (UnimplementedAssistAgentServer) mustEmbedUnimplementedAssistAgentServer() {}

// UnsafeAssistAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistAgentServer will
// result in compilation errors.
type UnsafeAssistAgentServer interface {
	mustEmbedUnimplementedAssistAgentServer()
}

func RegisterAssistAgentServer(s grpc.ServiceRegistrar, srv AssistAgentServer) {
	s.RegisterService(&AssistAgent_ServiceDesc, srv)
}

func _AssistAgent_GenRsaKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenRsaKeyPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).GenRsaKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/GenRsaKeyPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).GenRsaKeyPair(ctx, req.(*GenRsaKeyPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_RmRsaKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRsaKeyPairReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).RmRsaKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/RmRsaKeyPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).RmRsaKeyPair(ctx, req.(*RemoveRsaKeyPairReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_EncryptText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).EncryptText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/EncryptText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).EncryptText(ctx, req.(*EncryptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_DecryptText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).DecryptText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/DecryptText",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).DecryptText(ctx, req.(*DecryptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_CheckKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).CheckKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/CheckKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).CheckKey(ctx, req.(*CheckKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_CreateSecretParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretParamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).CreateSecretParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/CreateSecretParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).CreateSecretParam(ctx, req.(*CreateSecretParamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_GetSecretParamValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretParamValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).GetSecretParamValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/GetSecretParamValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).GetSecretParamValue(ctx, req.(*GetSecretParamValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_SignData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).SignData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/SignData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).SignData(ctx, req.(*SignDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_VerifySignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).VerifySignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AssistAgent/VerifySignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).VerifySignature(ctx, req.(*VerifySignatureReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssistAgent_ServiceDesc is the grpc.ServiceDesc for AssistAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssistAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AssistAgent",
	HandlerType: (*AssistAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenRsaKeyPair",
			Handler:    _AssistAgent_GenRsaKeyPair_Handler,
		},
		{
			MethodName: "RmRsaKeyPair",
			Handler:    _AssistAgent_RmRsaKeyPair_Handler,
		},
		{
			MethodName: "EncryptText",
			Handler:    _AssistAgent_EncryptText_Handler,
		},
		{
			MethodName: "DecryptText",
			Handler:    _AssistAgent_DecryptText_Handler,
		},
		{
			MethodName: "CheckKey",
			Handler:    _AssistAgent_CheckKey_Handler,
		},
		{
			MethodName: "CreateSecretParam",
			Handler:    _AssistAgent_CreateSecretParam_Handler,
		},
		{
			MethodName: "GetSecretParamValue",
			Handler:    _AssistAgent_GetSecretParamValue_Handler,
		},
		{
			MethodName: "SignData",
			Handler:    _AssistAgent_SignData_Handler,
		},
		{
			MethodName: "VerifySignature",
			Handler:    _AssistAgent_VerifySignature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agrpc.proto",
}
