// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative agrpc.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: agrpc.proto

package agrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RespStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	ErrMessage string `protobuf:"bytes,2,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
}

func (x *RespStatus) Reset() {
	*x = RespStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespStatus) ProtoMessage() {}

func (x *RespStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespStatus.ProtoReflect.Descriptor instead.
func (*RespStatus) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{0}
}

func (x *RespStatus) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RespStatus) GetErrMessage() string {
	if x != nil {
		return x.ErrMessage
	}
	return ""
}

type KeyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPairId        string `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PublicKey        string `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CreatedTimestamp int64  `protobuf:"varint,3,opt,name=createdTimestamp,proto3" json:"createdTimestamp,omitempty"`
	ExpiredTimestamp int64  `protobuf:"varint,4,opt,name=expiredTimestamp,proto3" json:"expiredTimestamp,omitempty"`
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{1}
}

func (x *KeyInfo) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

func (x *KeyInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeyInfo) GetCreatedTimestamp() int64 {
	if x != nil {
		return x.CreatedTimestamp
	}
	return 0
}

func (x *KeyInfo) GetExpiredTimestamp() int64 {
	if x != nil {
		return x.ExpiredTimestamp
	}
	return 0
}

// GenRsaKeyPair api
type GenRsaKeyPairReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPairId string `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	Timeout   int32  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *GenRsaKeyPairReq) Reset() {
	*x = GenRsaKeyPairReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenRsaKeyPairReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenRsaKeyPairReq) ProtoMessage() {}

func (x *GenRsaKeyPairReq) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenRsaKeyPairReq.ProtoReflect.Descriptor instead.
func (*GenRsaKeyPairReq) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{2}
}

func (x *GenRsaKeyPairReq) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

func (x *GenRsaKeyPairReq) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type GenRsaKeyPairResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	KeyInfo *KeyInfo    `protobuf:"bytes,2,opt,name=keyInfo,proto3" json:"keyInfo,omitempty"`
}

func (x *GenRsaKeyPairResp) Reset() {
	*x = GenRsaKeyPairResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenRsaKeyPairResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenRsaKeyPairResp) ProtoMessage() {}

func (x *GenRsaKeyPairResp) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenRsaKeyPairResp.ProtoReflect.Descriptor instead.
func (*GenRsaKeyPairResp) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{3}
}

func (x *GenRsaKeyPairResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GenRsaKeyPairResp) GetKeyInfo() *KeyInfo {
	if x != nil {
		return x.KeyInfo
	}
	return nil
}

// Encrypt api
type EncryptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPairId string `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	PlainText string `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
}

func (x *EncryptReq) Reset() {
	*x = EncryptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptReq) ProtoMessage() {}

func (x *EncryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptReq.ProtoReflect.Descriptor instead.
func (*EncryptReq) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptReq) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

func (x *EncryptReq) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

type EncryptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CipherText string      `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
}

func (x *EncryptResp) Reset() {
	*x = EncryptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResp) ProtoMessage() {}

func (x *EncryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResp.ProtoReflect.Descriptor instead.
func (*EncryptResp) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EncryptResp) GetCipherText() string {
	if x != nil {
		return x.CipherText
	}
	return ""
}

// Decrypt api
type DecryptReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPairId  string `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
	CipherText string `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
}

func (x *DecryptReq) Reset() {
	*x = DecryptReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptReq) ProtoMessage() {}

func (x *DecryptReq) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptReq.ProtoReflect.Descriptor instead.
func (*DecryptReq) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{6}
}

func (x *DecryptReq) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

func (x *DecryptReq) GetCipherText() string {
	if x != nil {
		return x.CipherText
	}
	return ""
}

type DecryptResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PlainText string      `protobuf:"bytes,2,opt,name=plainText,proto3" json:"plainText,omitempty"`
}

func (x *DecryptResp) Reset() {
	*x = DecryptResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecryptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResp) ProtoMessage() {}

func (x *DecryptResp) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResp.ProtoReflect.Descriptor instead.
func (*DecryptResp) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{7}
}

func (x *DecryptResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DecryptResp) GetPlainText() string {
	if x != nil {
		return x.PlainText
	}
	return ""
}

// CheckKey api
type CheckKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyPairId string `protobuf:"bytes,1,opt,name=keyPairId,proto3" json:"keyPairId,omitempty"`
}

func (x *CheckKeyReq) Reset() {
	*x = CheckKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKeyReq) ProtoMessage() {}

func (x *CheckKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKeyReq.ProtoReflect.Descriptor instead.
func (*CheckKeyReq) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{8}
}

func (x *CheckKeyReq) GetKeyPairId() string {
	if x != nil {
		return x.KeyPairId
	}
	return ""
}

type CheckKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	KeyInfos []*KeyInfo  `protobuf:"bytes,2,rep,name=keyInfos,proto3" json:"keyInfos,omitempty"`
}

func (x *CheckKeyResp) Reset() {
	*x = CheckKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_agrpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKeyResp) ProtoMessage() {}

func (x *CheckKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_agrpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKeyResp.ProtoReflect.Descriptor instead.
func (*CheckKeyResp) Descriptor() ([]byte, []int) {
	return file_agrpc_proto_rawDescGZIP(), []int{9}
}

func (x *CheckKeyResp) GetStatus() *RespStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CheckKeyResp) GetKeyInfos() []*KeyInfo {
	if x != nil {
		return x.KeyInfos
	}
	return nil
}

var File_agrpc_proto protoreflect.FileDescriptor

var file_agrpc_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x4c, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x2a, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x10, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x4a, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x61, 0x4b, 0x65, 0x79,
	0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61,
	0x69, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50,
	0x61, 0x69, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22,
	0x6a, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x61, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x29, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x48, 0x0a, 0x0a, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79,
	0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65,
	0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x69,
	0x6e, 0x54, 0x65, 0x78, 0x74, 0x22, 0x59, 0x0a, 0x0b, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x4a, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1c,
	0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x22, 0x57, 0x0a, 0x0b,
	0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x69, 0x6e,
	0x54, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x69,
	0x6e, 0x54, 0x65, 0x78, 0x74, 0x22, 0x2b, 0x0a, 0x0b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72,
	0x49, 0x64, 0x22, 0x67, 0x0a, 0x0c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4b, 0x65, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x32, 0x82, 0x02, 0x0a, 0x0b,
	0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x0d, 0x47,
	0x65, 0x6e, 0x52, 0x73, 0x61, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x52, 0x73, 0x61, 0x4b, 0x65, 0x79, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x47, 0x65, 0x6e, 0x52, 0x73, 0x61, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0b, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0b, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x4b, 0x65, 0x79, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6c, 0x69, 0x79, 0x75, 0x6e, 0x2f, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x5f, 0x61, 0x73, 0x73,
	0x69, 0x73, 0x74, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x69, 0x70, 0x63, 0x2f, 0x61, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_agrpc_proto_rawDescOnce sync.Once
	file_agrpc_proto_rawDescData = file_agrpc_proto_rawDesc
)

func file_agrpc_proto_rawDescGZIP() []byte {
	file_agrpc_proto_rawDescOnce.Do(func() {
		file_agrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_agrpc_proto_rawDescData)
	})
	return file_agrpc_proto_rawDescData
}

var file_agrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agrpc_proto_goTypes = []interface{}{
	(*RespStatus)(nil),        // 0: protos.RespStatus
	(*KeyInfo)(nil),           // 1: protos.KeyInfo
	(*GenRsaKeyPairReq)(nil),  // 2: protos.GenRsaKeyPairReq
	(*GenRsaKeyPairResp)(nil), // 3: protos.GenRsaKeyPairResp
	(*EncryptReq)(nil),        // 4: protos.EncryptReq
	(*EncryptResp)(nil),       // 5: protos.EncryptResp
	(*DecryptReq)(nil),        // 6: protos.DecryptReq
	(*DecryptResp)(nil),       // 7: protos.DecryptResp
	(*CheckKeyReq)(nil),       // 8: protos.CheckKeyReq
	(*CheckKeyResp)(nil),      // 9: protos.CheckKeyResp
}
var file_agrpc_proto_depIdxs = []int32{
	0,  // 0: protos.GenRsaKeyPairResp.status:type_name -> protos.RespStatus
	1,  // 1: protos.GenRsaKeyPairResp.keyInfo:type_name -> protos.KeyInfo
	0,  // 2: protos.EncryptResp.status:type_name -> protos.RespStatus
	0,  // 3: protos.DecryptResp.status:type_name -> protos.RespStatus
	0,  // 4: protos.CheckKeyResp.status:type_name -> protos.RespStatus
	1,  // 5: protos.CheckKeyResp.keyInfos:type_name -> protos.KeyInfo
	2,  // 6: protos.AssistAgent.GenRsaKeyPair:input_type -> protos.GenRsaKeyPairReq
	4,  // 7: protos.AssistAgent.EncryptText:input_type -> protos.EncryptReq
	6,  // 8: protos.AssistAgent.DecryptText:input_type -> protos.DecryptReq
	8,  // 9: protos.AssistAgent.CheckKey:input_type -> protos.CheckKeyReq
	3,  // 10: protos.AssistAgent.GenRsaKeyPair:output_type -> protos.GenRsaKeyPairResp
	5,  // 11: protos.AssistAgent.EncryptText:output_type -> protos.EncryptResp
	7,  // 12: protos.AssistAgent.DecryptText:output_type -> protos.DecryptResp
	9,  // 13: protos.AssistAgent.CheckKey:output_type -> protos.CheckKeyResp
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_agrpc_proto_init() }
func file_agrpc_proto_init() {
	if File_agrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_agrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenRsaKeyPairReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenRsaKeyPairResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecryptResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_agrpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agrpc_proto_goTypes,
		DependencyIndexes: file_agrpc_proto_depIdxs,
		MessageInfos:      file_agrpc_proto_msgTypes,
	}.Build()
	File_agrpc_proto = out.File
	file_agrpc_proto_rawDesc = nil
	file_agrpc_proto_goTypes = nil
	file_agrpc_proto_depIdxs = nil
}
