// Package version just contains constant version string of assist agent, which
// should be autogenerated on building
package version

// AssistVersion is the version string of agent
var AssistVersion string = "1.0.0.1"
var GitCommitHash string = ""
