#!/bin/bash

# suse enterprise linux server
agentwatch='agentwatch.suse'

# 1. check and copy files

rm -f $des_dir/usr/sbin/aliyun-service

# 1. check and copy files
file_list="
$src_dir/data/$issue/service/$agentwatch:$des_dir/etc/init.d/agentwatch
"

for pair in $file_list; do
    src_file=$(echo $pair | awk -F':' '{print $1}')
    des_file=$(echo $pair | awk -F':' '{print $2}')
    if [ ! -e "$src_file" ]; then
        echo "xxx: $src_file not exist"
        exit 1
    fi
    if [ -e "$des_file" ]; then
        src_md5sum=$(md5sum "$src_file" 2> /dev/null | awk '{print $1}')
        des_md5sum=$(md5sum "$des_file" 2> /dev/null | awk '{print $1}')
        if [ "$src_md5sum" == "$des_md5sum" ]; then
            continue
        fi
    fi
    # do copy
    cp -f "$src_file" "$des_file"
    chmod a+x $des_file
    if [ $? -ne 0 ]; then
        echo "xxx: failed to update $des_file"
        exit 1
    fi
done

ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun-service $des_dir/usr/sbin/aliyun-service
ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun_installer $des_dir/usr/sbin/aliyun_installer

# 2. add agentwatch service to boot on
mkdir -p $des_dir/aliyun-bin 1>/dev/null 2>&1
echo "chkconfig --add agentwatch" > $des_dir/aliyun-bin/add-agent-watch
echo "chkconfig agentwatch on" >> $des_dir/aliyun-bin/add-agent-watch

# clear gshelld init script in old image
if [ -e "$des_dir/etc/init.d/gshelld" ]; then
    echo "chkconfig --del gshelld" >> $des_dir/aliyun-bin/add-agent-watch
    echo "rm -rf /etc/init.d/gshelld" >> $des_dir/aliyun-bin/add-agent-watch
fi

[ -e "$des_dir/var/lock/agentwatch" ] && rm -f "$des_dir/var/lock/agentwatch"

chmod 777 $des_dir/aliyun-bin/add-agent-watch 1>/dev/null 2>&1
. "$des_dir/aliyun-bin/add-agent-watch"

ret=$?
rm -rf $des_dir/aliyun-bin 1>/dev/null 2>&1
if [ $ret -ne 0 ]; then
    echo "3223:failed to add $agentwatch service."
    exit 1
fi


# 3. fstab
# opensuse 13 can't add xenfs to /etc/fstab, otherwise image couldn't boot on


#echo "0:success"
