// Copyright 2013 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by genznmap.go; DO NOT EDIT.
// Based on information from https://raw.githubusercontent.com/unicode-org/cldr/master/common/supplemental/windowsZones.xml

package timetool

var nmaps = map[string]string{
	"Egypt Standard Time":             "Africa/Cairo",           // EET, EET
	"Morocco Standard Time":           "Africa/Casablanca",      // +00, +01
	"South Africa Standard Time":      "Africa/Johannesburg",    // SAST, SAST
	"South Sudan Standard Time":       "Africa/Juba",            // CAT, EAT
	"Sudan Standard Time":             "Africa/Khartoum",        // CAT, CAT
	"W. Central Africa Standard Time": "Africa/Lagos",           // WAT, WAT
	"E. Africa Standard Time":         "Africa/Nairobi",         // EAT, EAT
	"Sao Tome Standard Time":          "Africa/Sao_Tome",        // GMT, GMT
	"Libya Standard Time":             "Africa/Tripoli",         // EET, EET
	"Namibia Standard Time":           "Africa/Windhoek",        // CAT, CAT
	"Aleutian Standard Time":          "America/Adak",           // HST, HDT
	"Alaskan Standard Time":           "America/Anchorage",      // AKST, AKDT
	"Tocantins Standard Time":         "America/Araguaina",      // -03, -03
	"Paraguay Standard Time":          "America/Asuncion",       // -04, -03
	"Bahia Standard Time":             "America/Bahia",          // -03, -03
	"SA Pacific Standard Time":        "America/Bogota",         // -05, -05
	"Argentina Standard Time":         "America/Buenos_Aires",   // -03, -03
	"Eastern Standard Time (Mexico)":  "America/Cancun",         // EST, EST
	"Venezuela Standard Time":         "America/Caracas",        // -04, -04
	"SA Eastern Standard Time":        "America/Cayenne",        // -03, -03
	"Central Standard Time":           "America/Chicago",        // CST, CDT
	"Mountain Standard Time (Mexico)": "America/Chihuahua",      // MST, MDT
	"Central Brazilian Standard Time": "America/Cuiaba",         // -04, -04
	"Mountain Standard Time":          "America/Denver",         // MST, MDT
	"Greenland Standard Time":         "America/Godthab",        // -03, -02
	"Turks And Caicos Standard Time":  "America/Grand_Turk",     // EST, EDT
	"Central America Standard Time":   "America/Guatemala",      // CST, CST
	"Atlantic Standard Time":          "America/Halifax",        // AST, ADT
	"Cuba Standard Time":              "America/Havana",         // CST, CDT
	"US Eastern Standard Time":        "America/Indianapolis",   // EST, EDT
	"SA Western Standard Time":        "America/La_Paz",         // -04, -04
	"Pacific Standard Time":           "America/Los_Angeles",    // PST, PDT
	"Central Standard Time (Mexico)":  "America/Mexico_City",    // CST, CDT
	"Saint Pierre Standard Time":      "America/Miquelon",       // -03, -02
	"Montevideo Standard Time":        "America/Montevideo",     // -03, -03
	"Eastern Standard Time":           "America/New_York",       // EST, EDT
	"US Mountain Standard Time":       "America/Phoenix",        // MST, MST
	"Haiti Standard Time":             "America/Port-au-Prince", // EST, EDT
	"Magallanes Standard Time":        "America/Punta_Arenas",   // -03, -03
	"Canada Central Standard Time":    "America/Regina",         // CST, CST
	"Pacific SA Standard Time":        "America/Santiago",       // -04, -03
	"E. South America Standard Time":  "America/Sao_Paulo",      // -03, -03
	"Newfoundland Standard Time":      "America/St_Johns",       // NST, NDT
	"Pacific Standard Time (Mexico)":  "America/Tijuana",        // PST, PDT
	"Yukon Standard Time":             "America/Whitehorse",     // MST, MST
	"Central Asia Standard Time":      "Asia/Almaty",            // +06, +06
	"Jordan Standard Time":            "Asia/Amman",             // EET, EEST
	"Arabic Standard Time":            "Asia/Baghdad",           // +03, +03
	"Azerbaijan Standard Time":        "Asia/Baku",              // +04, +04
	"SE Asia Standard Time":           "Asia/Bangkok",           // +07, +07
	"Altai Standard Time":             "Asia/Barnaul",           // +07, +07
	"Middle East Standard Time":       "Asia/Beirut",            // EET, EEST
	"India Standard Time":             "Asia/Calcutta",          // IST, IST
	"Transbaikal Standard Time":       "Asia/Chita",             // +09, +09
	"Sri Lanka Standard Time":         "Asia/Colombo",           // +0530, +0530
	"Syria Standard Time":             "Asia/Damascus",          // EET, EEST
	"Bangladesh Standard Time":        "Asia/Dhaka",             // +06, +06
	"Arabian Standard Time":           "Asia/Dubai",             // +04, +04
	"West Bank Standard Time":         "Asia/Hebron",            // EET, EEST
	"W. Mongolia Standard Time":       "Asia/Hovd",              // +07, +07
	"North Asia East Standard Time":   "Asia/Irkutsk",           // +08, +08
	"Israel Standard Time":            "Asia/Jerusalem",         // IST, IDT
	"Afghanistan Standard Time":       "Asia/Kabul",             // +0430, +0430
	"Russia Time Zone 11":             "Asia/Kamchatka",         // +12, +12
	"Pakistan Standard Time":          "Asia/Karachi",           // PKT, PKT
	"Nepal Standard Time":             "Asia/Katmandu",          // +0545, +0545
	"North Asia Standard Time":        "Asia/Krasnoyarsk",       // +07, +07
	"Magadan Standard Time":           "Asia/Magadan",           // +11, +11
	"N. Central Asia Standard Time":   "Asia/Novosibirsk",       // +07, +07
	"Omsk Standard Time":              "Asia/Omsk",              // +06, +06
	"North Korea Standard Time":       "Asia/Pyongyang",         // KST, KST
	"Qyzylorda Standard Time":         "Asia/Qyzylorda",         // +05, +05
	"Myanmar Standard Time":           "Asia/Rangoon",           // +0630, +0630
	"Arab Standard Time":              "Asia/Riyadh",            // +03, +03
	"Sakhalin Standard Time":          "Asia/Sakhalin",          // +11, +11
	"Korea Standard Time":             "Asia/Seoul",             // KST, KST
	"China Standard Time":             "Asia/Shanghai",          // CST, CST
	"Singapore Standard Time":         "Asia/Singapore",         // +08, +08
	"Russia Time Zone 10":             "Asia/Srednekolymsk",     // +11, +11
	"Taipei Standard Time":            "Asia/Taipei",            // CST, CST
	"West Asia Standard Time":         "Asia/Tashkent",          // +05, +05
	"Georgian Standard Time":          "Asia/Tbilisi",           // +04, +04
	"Iran Standard Time":              "Asia/Tehran",            // +0330, +0430
	"Tokyo Standard Time":             "Asia/Tokyo",             // JST, JST
	"Tomsk Standard Time":             "Asia/Tomsk",             // +07, +07
	"Ulaanbaatar Standard Time":       "Asia/Ulaanbaatar",       // +08, +08
	"Vladivostok Standard Time":       "Asia/Vladivostok",       // +10, +10
	"Yakutsk Standard Time":           "Asia/Yakutsk",           // +09, +09
	"Ekaterinburg Standard Time":      "Asia/Yekaterinburg",     // +05, +05
	"Caucasus Standard Time":          "Asia/Yerevan",           // +04, +04
	"Azores Standard Time":            "Atlantic/Azores",        // -01, +00
	"Cape Verde Standard Time":        "Atlantic/Cape_Verde",    // -01, -01
	"Greenwich Standard Time":         "Atlantic/Reykjavik",     // GMT, GMT
	"Cen. Australia Standard Time":    "Australia/Adelaide",     // ACST, ACDT
	"E. Australia Standard Time":      "Australia/Brisbane",     // AEST, AEST
	"AUS Central Standard Time":       "Australia/Darwin",       // ACST, ACST
	"Aus Central W. Standard Time":    "Australia/Eucla",        // +0845, +0845
	"Tasmania Standard Time":          "Australia/Hobart",       // AEST, AEDT
	"Lord Howe Standard Time":         "Australia/Lord_Howe",    // +1030, +11
	"W. Australia Standard Time":      "Australia/Perth",        // AWST, AWST
	"AUS Eastern Standard Time":       "Australia/Sydney",       // AEST, AEDT
	"UTC-11":                          "Etc/GMT+11",             // -11, -11
	"Dateline Standard Time":          "Etc/GMT+12",             // -12, -12
	"UTC-02":                          "Etc/GMT+2",              // -02, -02
	"UTC-08":                          "Etc/GMT+8",              // -08, -08
	"UTC-09":                          "Etc/GMT+9",              // -09, -09
	"UTC+12":                          "Etc/GMT-12",             // +12, +12
	"UTC+13":                          "Etc/GMT-13",             // +13, +13
	"UTC":                             "Etc/UTC",                // UTC, UTC
	"Astrakhan Standard Time":         "Europe/Astrakhan",       // +04, +04
	"W. Europe Standard Time":         "Europe/Berlin",          // CET, CEST
	"GTB Standard Time":               "Europe/Bucharest",       // EET, EEST
	"Central Europe Standard Time":    "Europe/Budapest",        // CET, CEST
	"E. Europe Standard Time":         "Europe/Chisinau",        // EET, EEST
	"Turkey Standard Time":            "Europe/Istanbul",        // +03, +03
	"Kaliningrad Standard Time":       "Europe/Kaliningrad",     // EET, EET
	"FLE Standard Time":               "Europe/Kiev",            // EET, EEST
	"GMT Standard Time":               "Europe/London",          // GMT, BST
	"Belarus Standard Time":           "Europe/Minsk",           // +03, +03
	"Russian Standard Time":           "Europe/Moscow",          // MSK, MSK
	"Romance Standard Time":           "Europe/Paris",           // CET, CEST
	"Russia Time Zone 3":              "Europe/Samara",          // +04, +04
	"Saratov Standard Time":           "Europe/Saratov",         // +04, +04
	"Volgograd Standard Time":         "Europe/Volgograd",       // +03, +04
	"Central European Standard Time":  "Europe/Warsaw",          // CET, CEST
	"Mauritius Standard Time":         "Indian/Mauritius",       // +04, +04
	"Samoa Standard Time":             "Pacific/Apia",           // +13, +14
	"New Zealand Standard Time":       "Pacific/Auckland",       // NZST, NZDT
	"Bougainville Standard Time":      "Pacific/Bougainville",   // +11, +11
	"Chatham Islands Standard Time":   "Pacific/Chatham",        // +1245, +1345
	"Easter Island Standard Time":     "Pacific/Easter",         // -06, -05
	"Fiji Standard Time":              "Pacific/Fiji",           // +12, +13
	"Central Pacific Standard Time":   "Pacific/Guadalcanal",    // +11, +11
	"Hawaiian Standard Time":          "Pacific/Honolulu",       // HST, HST
	"Line Islands Standard Time":      "Pacific/Kiritimati",     // +14, +14
	"Marquesas Standard Time":         "Pacific/Marquesas",      // -0930, -0930
	"Norfolk Standard Time":           "Pacific/Norfolk",        // +11, +12
	"West Pacific Standard Time":      "Pacific/Port_Moresby",   // +10, +10
	"Tonga Standard Time":             "Pacific/Tongatapu",      // +13, +13
}
