#!/bin/bash



# 0. env check and prepare
if [ "$issue" != "ubuntu" ]; then
    echo "xxx: wrong image type"
    exit 1
fi

if [ "$big" == "10" -o "$big" == "12" -o "$big" == "14" ]; then
    agentwatch="agentwatch.ubuntu12"
elif [ "$big" == "16" ]; then
    agentwatch="agentwatch.ubuntu16"
else
    echo "xxx: wrong issue version: $big"
    exit 1
fi


assist_version=$(cat $src_dir/data/aliyun-service/version)
rm -f $des_dir/usr/sbin/aliyun-service
# 1. check and copy files
file_list="
$src_dir/data/$issue/service/$agentwatch:$des_dir/etc/init.d/agentwatch
"

for pair in $file_list; do
    src_file=$(echo $pair | awk -F':' '{print $1}')
    des_file=$(echo $pair | awk -F':' '{print $2}')
    if [ ! -e "$src_file" ]; then
        echo "xxx: $src_file not exist"
        exit 1
    fi
    if [ -e "$des_file" ]; then
        src_md5sum=$(md5sum "$src_file" 2> /dev/null | awk '{print $1}')
        des_md5sum=$(md5sum "$des_file" 2> /dev/null | awk '{print $1}')
        if [ "$src_md5sum" == "$des_md5sum" ]; then
            continue
        fi
    fi
    # do copy
    cp -f "$src_file" "$des_file"
    chmod a+x $des_file
    if [ $? -ne 0 ]; then
        echo "xxx: failed to update $des_file"
        exit 1
    fi
done

ln -sf /usr/local/share/aliyun-assist/$assist_version/aliyun-service $des_dir/usr/sbin/aliyun-service

# 2. add agentwatch service to boot on
mkdir -p $des_dir/aliyun-bin 1>/dev/null 2>&1
echo "update-rc.d agentwatch defaults" > $des_dir/aliyun-bin/add-agent-watch

# clear gshelld init script in old image
if [ -e "$des_dir/etc/init.d/gshelld" ]; then
    echo "rm -rf /etc/init.d/gshelld" >> $des_dir/aliyun-bin/add-agent-watch
    echo "update-rc.d -f gshelld remove" >> $des_dir/aliyun-bin/add-agent-watch
fi

[ -e "$des_dir/var/lock/agentwatch" ] && rm -f "$des_dir/var/lock/agentwatch"

chmod 777 $des_dir/aliyun-bin/add-agent-watch 1>/dev/null 2>&1
chroot $des_dir "add-agent-watch" 1>/dev/null 2>&1

ret=$?
rm -rf $des_dir/aliyun-bin 1>/dev/null 2>&1
if [ $ret -ne 0 ]; then
    glogger -o "[`now`] 3223:failed to add $agentwatch service (err:$ret)." -t $default_time 1>/dev/null 2>&1
    echo "3223:failed to add $agentwatch service."
    exit 1
fi



# 3. check /etc/fstab
sed -i '/^none.*\/proc\/xen.*xenfs/d' $des_dir/etc/fstab
if [ $? -ne 0 ]; then
    echo "3224: failed to modify $des_dir/etc/fstab"
    exit 1
fi


#echo "0:success"
