// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: configure.proto

package agrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssistAgentClient is the client API for AssistAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistAgentClient interface {
	GetConf(ctx context.Context, in *GetConfReq, opts ...grpc.CallOption) (*GetConfResp, error)
	SetConf(ctx context.Context, in *SetConfReq, opts ...grpc.CallOption) (*SetConfResp, error)
	ReloadConf(ctx context.Context, in *ReloadConfReq, opts ...grpc.CallOption) (*ReloadConfResp, error)
}

type assistAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistAgentClient(cc grpc.ClientConnInterface) AssistAgentClient {
	return &assistAgentClient{cc}
}

func (c *assistAgentClient) GetConf(ctx context.Context, in *GetConfReq, opts ...grpc.CallOption) (*GetConfResp, error) {
	out := new(GetConfResp)
	err := c.cc.Invoke(ctx, "/configure.AssistAgent/GetConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) SetConf(ctx context.Context, in *SetConfReq, opts ...grpc.CallOption) (*SetConfResp, error) {
	out := new(SetConfResp)
	err := c.cc.Invoke(ctx, "/configure.AssistAgent/SetConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistAgentClient) ReloadConf(ctx context.Context, in *ReloadConfReq, opts ...grpc.CallOption) (*ReloadConfResp, error) {
	out := new(ReloadConfResp)
	err := c.cc.Invoke(ctx, "/configure.AssistAgent/ReloadConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistAgentServer is the server API for AssistAgent service.
// All implementations must embed UnimplementedAssistAgentServer
// for forward compatibility
type AssistAgentServer interface {
	GetConf(context.Context, *GetConfReq) (*GetConfResp, error)
	SetConf(context.Context, *SetConfReq) (*SetConfResp, error)
	ReloadConf(context.Context, *ReloadConfReq) (*ReloadConfResp, error)
	mustEmbedUnimplementedAssistAgentServer()
}

// UnimplementedAssistAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAssistAgentServer struct {
}

func (UnimplementedAssistAgentServer) GetConf(context.Context, *GetConfReq) (*GetConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConf not implemented")
}
func (UnimplementedAssistAgentServer) SetConf(context.Context, *SetConfReq) (*SetConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConf not implemented")
}
func (UnimplementedAssistAgentServer) ReloadConf(context.Context, *ReloadConfReq) (*ReloadConfResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadConf not implemented")
}
func (UnimplementedAssistAgentServer) mustEmbedUnimplementedAssistAgentServer() {}

// UnsafeAssistAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistAgentServer will
// result in compilation errors.
type UnsafeAssistAgentServer interface {
	mustEmbedUnimplementedAssistAgentServer()
}

func RegisterAssistAgentServer(s grpc.ServiceRegistrar, srv AssistAgentServer) {
	s.RegisterService(&AssistAgent_ServiceDesc, srv)
}

func _AssistAgent_GetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).GetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configure.AssistAgent/GetConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).GetConf(ctx, req.(*GetConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_SetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).SetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configure.AssistAgent/SetConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).SetConf(ctx, req.(*SetConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistAgent_ReloadConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistAgentServer).ReloadConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/configure.AssistAgent/ReloadConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistAgentServer).ReloadConf(ctx, req.(*ReloadConfReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AssistAgent_ServiceDesc is the grpc.ServiceDesc for AssistAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssistAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configure.AssistAgent",
	HandlerType: (*AssistAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConf",
			Handler:    _AssistAgent_GetConf_Handler,
		},
		{
			MethodName: "SetConf",
			Handler:    _AssistAgent_SetConf_Handler,
		},
		{
			MethodName: "ReloadConf",
			Handler:    _AssistAgent_ReloadConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configure.proto",
}
