// Code generated by protoc-gen-go. DO NOT EDIT.
// source: configure.proto

package agrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RespStatus struct {
	StatusCode           int32    `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	ErrMessage           string   `protobuf:"bytes,2,opt,name=errMessage,proto3" json:"errMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespStatus) Reset()         { *m = RespStatus{} }
func (m *RespStatus) String() string { return proto.CompactTextString(m) }
func (*RespStatus) ProtoMessage()    {}
func (*RespStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{0}
}

func (m *RespStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespStatus.Unmarshal(m, b)
}
func (m *RespStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespStatus.Marshal(b, m, deterministic)
}
func (m *RespStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespStatus.Merge(m, src)
}
func (m *RespStatus) XXX_Size() int {
	return xxx_messageInfo_RespStatus.Size(m)
}
func (m *RespStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RespStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RespStatus proto.InternalMessageInfo

func (m *RespStatus) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *RespStatus) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

type ConfItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfItem) Reset()         { *m = ConfItem{} }
func (m *ConfItem) String() string { return proto.CompactTextString(m) }
func (*ConfItem) ProtoMessage()    {}
func (*ConfItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{1}
}

func (m *ConfItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfItem.Unmarshal(m, b)
}
func (m *ConfItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfItem.Marshal(b, m, deterministic)
}
func (m *ConfItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfItem.Merge(m, src)
}
func (m *ConfItem) XXX_Size() int {
	return xxx_messageInfo_ConfItem.Size(m)
}
func (m *ConfItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfItem proto.InternalMessageInfo

func (m *ConfItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetConfReq struct {
	Runtime              bool     `protobuf:"varint,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfReq) Reset()         { *m = GetConfReq{} }
func (m *GetConfReq) String() string { return proto.CompactTextString(m) }
func (*GetConfReq) ProtoMessage()    {}
func (*GetConfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{2}
}

func (m *GetConfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfReq.Unmarshal(m, b)
}
func (m *GetConfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfReq.Marshal(b, m, deterministic)
}
func (m *GetConfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfReq.Merge(m, src)
}
func (m *GetConfReq) XXX_Size() int {
	return xxx_messageInfo_GetConfReq.Size(m)
}
func (m *GetConfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfReq proto.InternalMessageInfo

func (m *GetConfReq) GetRuntime() bool {
	if m != nil {
		return m.Runtime
	}
	return false
}

type GetConfResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Items                []*ConfItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConfResp) Reset()         { *m = GetConfResp{} }
func (m *GetConfResp) String() string { return proto.CompactTextString(m) }
func (*GetConfResp) ProtoMessage()    {}
func (*GetConfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{3}
}

func (m *GetConfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfResp.Unmarshal(m, b)
}
func (m *GetConfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfResp.Marshal(b, m, deterministic)
}
func (m *GetConfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfResp.Merge(m, src)
}
func (m *GetConfResp) XXX_Size() int {
	return xxx_messageInfo_GetConfResp.Size(m)
}
func (m *GetConfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfResp proto.InternalMessageInfo

func (m *GetConfResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetConfResp) GetItems() []*ConfItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type SetConfReq struct {
	Runtime              bool        `protobuf:"varint,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	CrossVersion         bool        `protobuf:"varint,2,opt,name=crossVersion,proto3" json:"crossVersion,omitempty"`
	Items                []*ConfItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfReq) Reset()         { *m = SetConfReq{} }
func (m *SetConfReq) String() string { return proto.CompactTextString(m) }
func (*SetConfReq) ProtoMessage()    {}
func (*SetConfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{4}
}

func (m *SetConfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfReq.Unmarshal(m, b)
}
func (m *SetConfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfReq.Marshal(b, m, deterministic)
}
func (m *SetConfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfReq.Merge(m, src)
}
func (m *SetConfReq) XXX_Size() int {
	return xxx_messageInfo_SetConfReq.Size(m)
}
func (m *SetConfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfReq proto.InternalMessageInfo

func (m *SetConfReq) GetRuntime() bool {
	if m != nil {
		return m.Runtime
	}
	return false
}

func (m *SetConfReq) GetCrossVersion() bool {
	if m != nil {
		return m.CrossVersion
	}
	return false
}

func (m *SetConfReq) GetItems() []*ConfItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type SetConfResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfResp) Reset()         { *m = SetConfResp{} }
func (m *SetConfResp) String() string { return proto.CompactTextString(m) }
func (*SetConfResp) ProtoMessage()    {}
func (*SetConfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{5}
}

func (m *SetConfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfResp.Unmarshal(m, b)
}
func (m *SetConfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfResp.Marshal(b, m, deterministic)
}
func (m *SetConfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfResp.Merge(m, src)
}
func (m *SetConfResp) XXX_Size() int {
	return xxx_messageInfo_SetConfResp.Size(m)
}
func (m *SetConfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfResp proto.InternalMessageInfo

func (m *SetConfResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReloadConfReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadConfReq) Reset()         { *m = ReloadConfReq{} }
func (m *ReloadConfReq) String() string { return proto.CompactTextString(m) }
func (*ReloadConfReq) ProtoMessage()    {}
func (*ReloadConfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{6}
}

func (m *ReloadConfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadConfReq.Unmarshal(m, b)
}
func (m *ReloadConfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadConfReq.Marshal(b, m, deterministic)
}
func (m *ReloadConfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadConfReq.Merge(m, src)
}
func (m *ReloadConfReq) XXX_Size() int {
	return xxx_messageInfo_ReloadConfReq.Size(m)
}
func (m *ReloadConfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadConfReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadConfReq proto.InternalMessageInfo

type ReloadConfResp struct {
	Status               *RespStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReloadConfResp) Reset()         { *m = ReloadConfResp{} }
func (m *ReloadConfResp) String() string { return proto.CompactTextString(m) }
func (*ReloadConfResp) ProtoMessage()    {}
func (*ReloadConfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2743bc0c876cc3bd, []int{7}
}

func (m *ReloadConfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadConfResp.Unmarshal(m, b)
}
func (m *ReloadConfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadConfResp.Marshal(b, m, deterministic)
}
func (m *ReloadConfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadConfResp.Merge(m, src)
}
func (m *ReloadConfResp) XXX_Size() int {
	return xxx_messageInfo_ReloadConfResp.Size(m)
}
func (m *ReloadConfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadConfResp.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadConfResp proto.InternalMessageInfo

func (m *ReloadConfResp) GetStatus() *RespStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*RespStatus)(nil), "configure.RespStatus")
	proto.RegisterType((*ConfItem)(nil), "configure.ConfItem")
	proto.RegisterType((*GetConfReq)(nil), "configure.GetConfReq")
	proto.RegisterType((*GetConfResp)(nil), "configure.GetConfResp")
	proto.RegisterType((*SetConfReq)(nil), "configure.SetConfReq")
	proto.RegisterType((*SetConfResp)(nil), "configure.SetConfResp")
	proto.RegisterType((*ReloadConfReq)(nil), "configure.ReloadConfReq")
	proto.RegisterType((*ReloadConfResp)(nil), "configure.ReloadConfResp")
}

func init() {
	proto.RegisterFile("configure.proto", fileDescriptor_2743bc0c876cc3bd)
}

var fileDescriptor_2743bc0c876cc3bd = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4b, 0xcb, 0xd3, 0x40,
	0x14, 0x35, 0x5f, 0xed, 0xeb, 0x46, 0x2d, 0x8c, 0x0f, 0x62, 0x17, 0x52, 0x66, 0x21, 0x75, 0x61,
	0x03, 0xd5, 0x95, 0x08, 0x52, 0x83, 0x88, 0xa0, 0x9b, 0x09, 0xb8, 0x70, 0x53, 0xa6, 0xe9, 0x6d,
	0x1c, 0x48, 0x66, 0xe2, 0xdc, 0x89, 0xe0, 0x5f, 0xf4, 0x57, 0x49, 0x5e, 0x4d, 0x0a, 0x15, 0x1f,
	0xab, 0xcc, 0x9c, 0x39, 0xe7, 0xdc, 0x73, 0x92, 0x0c, 0x2c, 0x12, 0xa3, 0x4f, 0x2a, 0x2d, 0x2d,
	0x6e, 0x0a, 0x6b, 0x9c, 0x61, 0xf3, 0x33, 0xc0, 0x3f, 0x02, 0x08, 0xa4, 0x22, 0x76, 0xd2, 0x95,
	0xc4, 0x9e, 0x00, 0x50, 0xbd, 0x8a, 0xcc, 0x11, 0x03, 0x6f, 0xe5, 0xad, 0xc7, 0x62, 0x80, 0x54,
	0xe7, 0x68, 0xed, 0x27, 0x24, 0x92, 0x29, 0x06, 0x37, 0x2b, 0x6f, 0x3d, 0x17, 0x03, 0x84, 0xbf,
	0x84, 0x59, 0x64, 0xf4, 0xe9, 0x83, 0xc3, 0x9c, 0x31, 0xb8, 0xad, 0x65, 0xde, 0xb8, 0xcc, 0x45,
	0xbd, 0x66, 0x0f, 0x60, 0xfc, 0x5d, 0x66, 0x65, 0x27, 0x6d, 0x36, 0xfc, 0x29, 0xc0, 0x7b, 0x74,
	0x95, 0x50, 0xe0, 0x37, 0x16, 0xc0, 0xd4, 0x96, 0xda, 0xa9, 0x56, 0x3a, 0x13, 0xdd, 0x96, 0xa7,
	0xe0, 0x9f, 0x79, 0x54, 0xb0, 0xe7, 0x30, 0x69, 0xa2, 0xd5, 0x3c, 0x7f, 0xfb, 0x70, 0xd3, 0xf7,
	0xec, 0x3b, 0x89, 0x96, 0xc4, 0x9e, 0xc1, 0x58, 0x39, 0xcc, 0x29, 0xb8, 0x59, 0x8d, 0xd6, 0xfe,
	0xf6, 0xfe, 0x80, 0xdd, 0x65, 0x16, 0x0d, 0x83, 0x97, 0x00, 0xf1, 0x5f, 0x04, 0x62, 0x1c, 0xee,
	0x24, 0xd6, 0x10, 0x7d, 0x46, 0x4b, 0xca, 0xe8, 0xba, 0xd5, 0x4c, 0x5c, 0x60, 0xfd, 0xd8, 0xd1,
	0x1f, 0xc7, 0xbe, 0x06, 0x3f, 0xfe, 0xef, 0x7e, 0x7c, 0x01, 0x77, 0x05, 0x66, 0x46, 0x1e, 0xdb,
	0xdc, 0xfc, 0x0d, 0xdc, 0x1b, 0x02, 0xff, 0xec, 0xb8, 0xfd, 0xe9, 0x81, 0xbf, 0x23, 0x52, 0xe4,
	0x76, 0x29, 0x6a, 0xc7, 0x5e, 0xc1, 0xb4, 0x7d, 0xff, 0x6c, 0xa8, 0xec, 0xbf, 0xdd, 0xf2, 0xd1,
	0x35, 0x98, 0x0a, 0x7e, 0xab, 0xd2, 0xc6, 0x57, 0xb4, 0xf1, 0x75, 0x6d, 0x7c, 0xa1, 0x8d, 0xaa,
	0x7f, 0xb4, 0x2b, 0xc2, 0x82, 0x8b, 0xd0, 0x83, 0xc2, 0xcb, 0xc7, 0xbf, 0x39, 0xa9, 0x4c, 0xde,
	0xbe, 0xfb, 0x12, 0xa5, 0xca, 0x7d, 0x2d, 0x0f, 0x9b, 0xc4, 0xe4, 0xa1, 0xcc, 0xd4, 0x8f, 0x52,
	0xb7, 0x8f, 0xbd, 0xac, 0x4b, 0xee, 0x93, 0x4c, 0xa1, 0x76, 0xa1, 0xd2, 0x0e, 0x6d, 0x61, 0x4d,
	0x82, 0x44, 0xe1, 0xd9, 0x31, 0x94, 0xa9, 0x2d, 0x92, 0xc3, 0xa4, 0xbe, 0x41, 0x2f, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xaf, 0xa1, 0x6d, 0x82, 0x54, 0x03, 0x00, 0x00,
}
